version: '3'
services:
  db:
    image: postgres:14
    environment:
       - POSTGRES_PASSWORD=default
       - POSTGRES_USER=default
       - POSTGRES_DB=Bookstore
    ports:
       - "5432:5432"
    volumes:
      - ./db/DB.sql:/docker-entrypoint-initdb.d/DB.sql
      